name: Build & upload an Android App to Play Store
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/* ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Retrieve base64 keystore and decode it to a file
        env:
            KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 --decode > "${{ github.workspace }}/motow.jks"

      - name: Upload keystore file
        uses: actions/upload-artifact@v3
        with:
          name: motow.jks
          path: ${{ github.workspace }}/motow.jks

      - name: ðŸ“ðŸ” Create keystore.properties file
        env:
            KEYSTORE_PROPERTIES_PATH: ${{ github.workspace }}/android/key.properties
        run: |
            echo 'StoreFile=${{ github.workspace }}/motow.jks' > $KEYSTORE_PROPERTIES_PATH
            echo 'KeyAlias=${{ secrets.KEYSTORE_KEY_ALIAS }}' >> $KEYSTORE_PROPERTIES_PATH
            echo 'StorePassword=${{ secrets.KEYSTORE_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH
            echo 'KeyPassword=${{ secrets.KEYSTORE_KEY_PASSWORD }}' >> $KEYSTORE_PROPERTIES_PATH

      - name: test print
        run: ${{ github.workspace }}/android/key.properties

      - name: Display Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get
        
      - name: Build Android App
        run: flutter build appbundle --release

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install bundler
        run: gem install bundler
        working-directory: android

      - name: Install dependencies
        run: bundle install
        working-directory: android

      - name: Update fastlane plugins
        run: bundle exec fastlane update_plugins
        working-directory: android

      - name: Create service credential file
        run: echo -n "${{ secrets.SERVICE_CREDENTIAL_PLAYSTORE }}" | base64 -d > ${{ github.workspace }}/service_credential.json

      - name: Upload service credential file
        uses: actions/upload-artifact@v3
        with:
          name: service_credential.json
          path: ${{ github.workspace }}/service_credential.json

      - name: Upload Android App to Play Store with fastlane
        run: bundle exec fastlane playstore --verbose
        env:
          SERVICE_CREDENTIAL_PLAYSTORE: ${{ github.workspace }}/service_credential.json
          APPBUNDLE_PATH: ${{ github.workspace }}/build/app/outputs/bundle/release/app-release.aab
        working-directory: android
